#!/bin/bash
# Copyright 2026 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0
#
# Regenerates the shared configurations (.golangci.yml, deny.toml) 
#
# Usage: scripts/sync-repos.sh [repo...]   (default: all repos)
#
set -euo pipefail

ORG=${ORG:-veraison}
BRANCH=${BRANCH:-veraison-ci/sync-configs}
CI_ROOT=$(cd "$(dirname "$0")/.." && pwd)
WORK=$(mktemp -d)
trap 'rm -rf "${WORK}"' EXIT

TITLE="chore(ci): sync shared configurations from veraison/ci"
BODY="Linter configuration has changed in veraison/ci.
This pull request is created automatically to keep the local on in sync."

is_managed() {
	local repo=$1 file
	for file in .golangci.yml deny.toml; do
		if gh api "repos/${ORG}/${repo}/contents/${file}" --jq .content 2>/dev/null |
			base64 -d 2>/dev/null | grep -q '^# Generated by veraison/ci'; then
			return 0
		fi
	done
	return 1
}

if [ $# -gt 0 ]; then
	repos=("$@")
else
	mapfile -t repos < <(gh repo list "${ORG}" --no-archived --source --limit 1000 --json name --jq '.[].name')
fi

sync_repo() {
	local repo=$1 dir="${WORK}/$1" url
	gh repo clone "${ORG}/${repo}" "${dir}" -- --quiet --depth 1 || return 1
	cd "${dir}" || return 1
	python3 "${CI_ROOT}/scripts/sync-config.py" --source "${CI_ROOT}/configs" >/dev/null || return 1
	if [ -z "$(git status --porcelain)" ]; then
		echo "${repo}: up to date"
		return 0
	fi
	git checkout --quiet -B "${BRANCH}" || return 1
	git commit --quiet --signoff --all --message "${TITLE}" || return 1
	git push --quiet --force origin "${BRANCH}" || return 1
	if [ "$(gh pr view "${BRANCH}" --json state --jq .state 2>/dev/null)" = OPEN ]; then
		url=$(gh pr view "${BRANCH}" --json url --jq .url) || return 1
		echo "${repo}: updated ${url}"
	else
		url=$(gh pr create --head "${BRANCH}" --title "${TITLE}" --body "${BODY}") || return 1
		echo "${repo}: opened ${url}"
	fi
}

failed=0
for repo in "${repos[@]}"; do
	is_managed "${repo}" || continue
	if ! (sync_repo "${repo}"); then
		echo "::error::${repo}: sync failed"
		failed=1
	fi
done
exit "${failed}"
