#!/usr/bin/env python3
# Copyright 2026 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0
"""Generates the shared tool configurations of a Veraison project.

Each generated file is the common configuration from veraison/ci merged with
the optional project specific additions of the project:

    .golangci.yml  <- configs/.golangci.yml + .golangci.project.yml (per repo)
    deny.toml      <- configs/deny.toml     + deny.project.toml (per repo)
"""

import argparse
import sys
import textwrap
from functools import partial
from pathlib import Path

import requests
import tomlkit
import yaml
from deepmerge import Merger

CONFIG_SOURCE = "https://raw.githubusercontent.com/veraison/ci/main/configs"
SCRIPT_URL = "https://raw.githubusercontent.com/veraison/ci/main/scripts/sync-config.py"

# (destination, project specific additions)
CONFIGS = [
    (".golangci.yml", ".golangci.project.yml"),
    ("deny.toml", "deny.project.toml"),
]

# Register parsers (yml, toml)
FORMATS = {
    ".toml": (tomlkit.parse, tomlkit.dumps),
    ".yml": (
        lambda text: yaml.safe_load(text) or {},
        partial(yaml.safe_dump, sort_keys=False, default_flow_style=False, width=1000),
    ),
}

def extend_unique(_config, _path, base, nxt):
    base.extend(v for v in nxt if v not in base)
    return base


# list and maps are merged, rest is overwritten
merge = Merger(
    [(dict, "merge"), (list, extend_unique)],
    ["override"],
    ["override"],
).merge


def header(target, project, comment="#"):
    return textwrap.indent(
        f"""\
Generated by veraison/ci from {CONFIG_SOURCE}/{target}
and optional {project}.
Do NOT EDIT: change {project} and regenerate with
  {SCRIPT_URL}
""",
        f"{comment} ",
    )

def format_of(name):
    suffix = Path(name).suffix
    return FORMATS[suffix]


def read_source(source, name):
    if source.startswith(("http://", "https://")):
        response = requests.get(f"{source}/{name}", timeout=30)
        response.raise_for_status()
        return response.text
    return Path(source, name).read_text()


def generate(source, target, project):
    parse, serialize = format_of(target)
    data = parse(read_source(source, target))
    additions = Path(project)
    if additions.is_file():
        data = merge(data, parse(additions.read_text()))
    return header(target, project) + serialize(data)


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--source", default=CONFIG_SOURCE)
    parser.add_argument("--check", action="store_true", help="only check if out of date")
    args = parser.parse_args()

    outdated = []
    for name, project in CONFIGS:
        target = Path(name)
        if not (target.is_file() or Path(project).is_file()):
            continue
        content = generate(args.source, name, project)
        if target.is_file() and target.read_text() == content:
            print(f"{name}: up to date")
        elif args.check:
            outdated.append(name)
            print(f"{name}: out of date")
        else:
            outdated.append(name)
            target.write_text(content)
            print(f"{name}: updated")

    if args.check and outdated:
        sys.exit(1)


if __name__ == "__main__":
    main()
